
name: Unit Tests for Lezer Parser
on:
  workflow_dispatch:
  workflow_call:

jobs:
  lezer_unit_tests:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./test/
    env:
      NODE_VERSION: 20
      PYTHON_VERSION: 3.8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm install

      - name: Build the parser
        run: npm run build

      - name: Run Lezer tests
        run: |
          npm test
